true_values:
  - "Y"
  - "YES"
  - "T"
  - "TRUE"
  - "OK"
  - "SURE"
  - "YEP"
  - "YUP"
  - "AFFIRMATIVE"
  - "AGREED"
  - "AYE"
  - "YEA"
  - "YEAH"
  - "CERTAINLY"
  - "DEFINITELY"
  - "POSITIVE"
  - "CORRECT"
  - "ACCEPTED"
  - "CONFIRM"
  - "APPROVED"
  - "AUTHORIZED"
  - "CONFIRMED"
  - "GRANTED"
  - "RIGHT"
  - "INDUBITABLY"
  - "ABSOLUTELY"
  - "ACK"
  - "ROGER"
  - "ACCEPT"
  - "ACC"
  - "AGREE"
  - "ACCORD"
  - "GO"
  - "PROCEED"
  - "CONSENT"
  - "SI"
  - "OUI"
  - "DA"
  - "JA"

false_values:
  - "N"
  - "NO"
  - "F"
  - "FALSE"
  - "NEGATIVE"
  - "NONE"
  - "NAY"
  - "NAH"
  - "NOP"
  - "NOPE"
  - "DISAGREE"
  - "DENIED"
  - "REJECTED"
  - "REFUSED"
  - "INCORRECT"
  - "WRONG"
  - "INVALID"
  - "UNTRUE"
  - "DISAPPROVED"
  - "UNAUTHORIZED"
  - "DECLINED"
  - "VETOED"
  - "CANCELED"
  - "CANCEL"
  - "ABORT"
  - "STOP"
  - "HALT"
  - "NON"
  - "NIX"
  - "NADA"
  - "NI"
  - "NEIN"
  - "NON"
  - "NYET"
  - "DENY"
  - "REFUTE"
  - "REJECT"
  - "DISSENT"